### ISSUE TITLE
./tmp/sigma.npy Error

### ISSUE THREAD

**Issue by drorhunvural** [rahmanidashti/STACP#2]
I am getting the following error in TimeAwareMF.py. Do I need to **/tmp.sigma.npy?** Do you know how can we solve this issue?

Thank you!

line 77, in train
    np.save("./tmp/sigma", sigma)

IOError: [Errno 2] No such file or directory: **'./tmp/sigma.npy'**

**Comment by rahmanidashti** [comment]
Thanks for your comment.

You only need to create two folders in the **STACP** folder: **tmp** and **result**. I have added them. Let me know if you have any other questions.
